// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto.Redis.Infra.Data.Context;

namespace Projeto.Redis.Infra.Data.Migrations
{
    [DbContext(typeof(ContextBase))]
    partial class ContextBaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Projeto.Redis.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Bairro");

                    b.Property<string>("Cep")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Cep");

                    b.Property<string>("Cidade")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Cidade");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Email");

                    b.Property<string>("Estado")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Estado");

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Nome");

                    b.Property<string>("Rua")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Rua");

                    b.Property<string>("Telefone")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Telefone");

                    b.Property<string>("Telefone2")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Telefone2");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
